# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6293795a156823e7310e9423e52a8a3243ccb279ef7ded073115fed48106d99ab41ba94e230cb53801619eaff957dbe9d5eede1c39212098899ee40c55d34620

test:
  secret_key_base: d28fa6e07b55094ac22d37c72eae3e62d36ec53972197381e3b913bbeaed3d69ac45aca3d79add22d0604698cd588410f0b271e56c11e88afbdd77fdc7a5e66b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
